-- Active: 1679829265554@@127.0.0.1@3306@restaurante_bd
/*Projeto: Bancos de Dados de um restaurante Simples.
Desenvolvido: Victor Hugo Marques
Tempo Estimado:  minutos. 

Descrição: Scritp cria todas as tabelas do banco de dados, assim como as conexões de chave estrangeira entre elas. 
Foi optado por apresentar neste arquivo único, por se tratar de poucas tabelas a principio.

Script voltado somente para criação inicial. Sendo executado somente uma vez para inicio de projeto. 
*/
DROP DATABASE IF EXISTS RESTAURANTE_BD;

/*CRIAR A DATABASE DO BAR*/
CREATE DATABASE RESTAURANTE_BD;

USE RESTAURANTE_BD;

/*TABELA GUARDA OS DEPARTAMENTOS EXISTENTES NA EMPRESA */
CREATE TABLE DEPARTAMENTO(
    ID_DEPARTAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DEPARTAMENTO VARCHAR(50) NOT NULL UNIQUE,
    DESCRICAO VARCHAR (200) NOT NULL
);

/*TABELA GUARDA DADOS DOS FUNCIONARIOS*/
CREATE TABLE IF NOT EXISTS FUNCIONARIO(
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO ENUM('Masculino', 'Feminino', 'Não informado') NOT NULL,
    CPF VARCHAR(15) NOT NULL UNIQUE,
    RG VARCHAR(15) NOT NULL UNIQUE,
    ID_DEPARTAMENTO INT
);

/*CONSTRAINT QUE RELACIONA O FUNCIONARIO AO SEU RESPECTIVO DEPARTAMENTO*/
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO) ON DELETE CASCADE;

/*TABELA GUARDA DADOS DOS CLIENTES DA EMPRESA*/
CREATE TABLE IF NOT EXISTS CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(15) UNIQUE,
    RG VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    SEXO ENUM('Masculino', 'Feminino', 'Não informado') NOT NULL
);

/*TABELA GUARDA AS INFORMACOES DOS FORNECEDORES*/
CREATE TABLE IF NOT EXISTS FORNECEDOR(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(17) NOT NULL UNIQUE,
    INSC_ESTADUAL VARCHAR(20) NOT NULL
);

/*TABELA GUARDA AS BATIDAS DE PONTO DOS FUNCIONARIOS*/
CREATE TABLE IF NOT EXISTS LISTA_PONTO(
    ID_PONTO INT PRIMARY KEY AUTO_INCREMENT,
    HORAS TIME(6) NOT NULL,
    DATA DATE NOT NULL,
    ID_FUNCIONARIO INT
);

ALTER TABLE LISTA_PONTO ADD CONSTRAINT FK_LISTA_PONTO_TO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE;