/*TABELAS A SEGUIR PERSISTEM OS DADOS RELACIONADOS A ENDEREÇO (PAIS, ESTADO, CIDADE, BAIRRO)*/

/*TABELA GUARDA OS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS PAIS(
	ID_PAIS INT PRIMARY KEY AUTO_INCREMENT,
	PAIS VARCHAR(30) NOT NULL
);

/*TABELA GUARDA OS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS ESTADO(
	ID_ESTADO INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO VARCHAR(30) NOT NULL,
	ID_PAIS INT
);

ALTER TABLE ESTADO ADD CONSTRAINT FK_ESTADO_TO_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE;

/*TABELA GUARDA AS CIDADES DOS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS CIDADE(
	ID_CIDADE INT PRIMARY KEY AUTO_INCREMENT,
	CIDADE VARCHAR(30) NOT NULL,
	ID_PAIS INT,
	ID_ESTADO INT
);

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_TO_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE;

ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_TO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO) ON DELETE CASCADE;

/*TABELA GUARDA OS BAIRROS DAS CIDADES DOS ESTADOS DOS PAISES PARA ENDERECO*/
CREATE TABLE IF NOT EXISTS BAIRRO(
	ID_BAIRRO INT PRIMARY KEY AUTO_INCREMENT,
	BAIRRO VARCHAR(30) NOT NULL,
	ID_PAIS INT,
	ID_ESTADO INT,
	ID_CIDADE INT
);

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_TO_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE;

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_TO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO) ON DELETE CASCADE;

ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_TO_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE) ON DELETE CASCADE;

/*TABELA GUARDA O ENDERECO DE CLIENTES E FUNCIONARIO*/
CREATE TABLE IF NOT EXISTS ENDERECO(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	ENDERECO VARCHAR(30) NOT NULL,
	NUMERO INT,
	ID_FUNCIONARIO INT,
	ID_CLIENTE INT,
	ID_FORNECEDOR INT,
	ID_PAIS INT,
	ID_ESTADO INT,
	ID_CIDADE INT,
	ID_BAIRRO INT
);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_CIDADE FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID_CIDADE) ON DELETE CASCADE;

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_TO_BAIRRO FOREIGN KEY(ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO) ON DELETE CASCADE;