/*TABELAS RELACINADAS AO PEDIDO

*/

/*TABELA GUARDA OS PEDIDOS PARA CONSUMO LOCAL E ENTREGA*/
CREATE TABLE IF NOT EXISTS PEDIDO(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    VALOR_TOTAL FLOAT NOT NULL,
    QUANT_ITENS INT NOT NULL,
    MESA INT,
    DATA DATE NOT NULL,
    HORA TIME NOT NULL,
    STATUS ENUM('P', 'E') NOT NULL, /*PRESENCIAL OU ENTREGA*/
    ID_CLIENTE INT,
    ID_FUNCIONARIO INT
);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_TO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE;

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_TO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE;

/*TABELA GUARDA AS INFORMAÇÕES DAS MOTOS DE ENTREGA*/
CREATE TABLE IF NOT EXISTS MOTO(
    ID_MOTO INT PRIMARY KEY AUTO_INCREMENT,
    PLACA VARCHAR(15) NOT NULL,
    RENAVAN VARCHAR(30) NOT NULL,
    ANO_FABRICACAO YEAR NOT NULL,
    DATA_COMPRA DATE NOT NULL
);

/*TABELA GUARDA AS INFORMAÇÕES DE PAGAMENTO*/
CREATE TABLE IF NOT EXISTS PAGAMENTO(
    ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_PAGAMENTO ENUM('CREDITO', 'DEBITO', 'DINHEIRO', 'PIX') NOT NULL,
    VALOR_ENTREGA FLOAT,
    VALOR_TOTAL FLOAT,
    ID_PEDIDO INT
);

ALTER TABLE PAGAMENTO ADD CONSTRAINT FK_PAGAMENTO_TO_PEDIDO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE;

/*TABELA GUARDA AS INFORMAÇÕESD E ENTREGA*/
CREATE TABLE IF NOT EXISTS ENTREGA(
    ID_ENTREGA INT PRIMARY KEY AUTO_INCREMENT,
    ROTA VARCHAR(200),
    ID_ENDERECO INT,
    ID_FUNCIONARIO INT,
    ID_PEDIDO INT,
    ID_MOTO INT
);

ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_TO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE;

ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_TO_PEDIDO FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE;

ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_TO_MOTO FOREIGN KEY(ID_MOTO) REFERENCES MOTO(ID_MOTO) ON DELETE CASCADE;

ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_TO_ENDERECO FOREIGN KEY(ID_ENDERECO) REFERENCES ENDERECO(ID_ENDERECO) ON DELETE CASCADE;

/*TABELA GUARDA A LISTA DE PRODUTOS DO PEDIDO*/
CREATE TABLE IF NOT EXISTS LISTA_PRODUTOS_PEDIDO(
    ID_LISTA_PRODUTOS_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT,
    ID_ITEM_MENU INT,
    QUANTIDADE INT,
    VALOR FLOAT
);

ALTER TABLE LISTA_PRODUTOS_PEDIDO ADD FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE;

ALTER TABLE LISTA_PRODUTOS_PEDIDO ADD FOREIGN KEY(ID_ITEM_MENU) REFERENCES ITEM_MENU(ID_ITEM_MENU) ON DELETE CASCADE;