/*TABELAS RELACIONADAS A PEDIDOS DE COMPRA*/

/*TABELA ONDE SE GUARDA AS ORDENS DE COMPRA*/
CREATE TABLE IF NOT EXISTS ORDEM_COMPRA(
    ID_ORDEM_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
    OBSERVACAO VARCHAR(100),
    QUANTIDADE_ITENS INT NOT NULL,
    VALOR_TOTAL FLOAT,
    TIPO_PAGAMENTO ENUM('CREDITO', 'DEBITO', 'DINHEIRO', 'PIX') NOT NULL,
    ID_FUNCIONARIO INT,
    ID_FORNECEDOR INT
);

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT FK_ORDEM_COMPRA_TO_FUNCIONARIO FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO) ON DELETE CASCADE;

ALTER TABLE ORDEM_COMPRA ADD CONSTRAINT FK_ORDEM_COMPRA_TO_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR) ON DELETE CASCADE;

/*TABELA GUARDA A LISTA DE PRODUTOS EM CADA COMPRA*/
CREATE TABLE IF NOT EXISTS LISTA_PRODUTOS_COMPRA(
    ID_ORDEM_COMPRA INT PRIMARY KEY AUTO_INCREMENT,
    ID_MATERIA_PRIMA INT,
    QUANTIDADE INT NOT NULL,
    VALOR FLOAT NOT NULL
);

ALTER TABLE LISTA_PRODUTOS_COMPRA ADD CONSTRAINT FK_PRODUTOS_COMPRA_TO_ORDEM_COMPRA FOREIGN KEY(ID_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA(ID_ORDEM_COMPRA) ON DELETE CASCADE;

ALTER TABLE LISTA_PRODUTOS_COMPRA ADD CONSTRAINT FK_PRODUTOS_COMPRA_TO_MATERIA_PRIMA FOREIGN KEY(ID_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(ID_MATERIA_PRIMA) ON DELETE CASCADE;